<a href="https://colab.research.google.com/github/chaezz/recomend-library/blob/master/Matrix_Factorization(200401.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
df_ratings = pd.read_csv('/content/drive/My Drive/Matrix Factorization(2020)/ratings.csv')
df_movies = pd.read_csv('/content/drive/My Drive/Matrix Factorization(2020)/movies.csv')


In [0]:
df_ratings.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [0]:
df_rentlist = pd.read_pickle('/content/drive/My Drive/Test 500x500 /500x500rentlist(수정).pkl')
df_rentlist['value'] = 1
df_rentlist.head()

회원번호           ISBN  value
0  47444.0  9788930206723      1
1  47444.0  9788991642638      1
2  47444.0  9788930232425      1
3  47444.0  9788937841989      1
4  47444.0  9788943309282      1

In [0]:
df_books = pd.read_csv('/content/drive/My Drive/Test 500x500 /itemtable500.csv', encoding='cp949')
df_books.head(10)

Unnamed: 0  ...  주제분류번호
0           0  ...     NaN
1           1  ...     NaN
2           2  ...     NaN
3           3  ...     NaN
4           4  ...     NaN
5           5  ...     NaN
6           6  ...     NaN
7           7  ...     NaN
8           8  ...     NaN
9           9  ...     NaN

[10 rows x 5 columns]

In [0]:
df_user_book_ratings = df_rentlist.pivot_table(
    index='회원번호',
    columns='ISBN',
    values='value'
).fillna(0)

In [0]:
df_user_book_ratings.head()

ISBN   9780060741693  9780198480648  ...  9791195788583  9788993632583 
회원번호                                 ...                               
126.0            0.0            0.0  ...            0.0             0.0
445.0            0.0            0.0  ...            0.0             0.0
489.0            0.0            0.0  ...            0.0             0.0
687.0            0.0            0.0  ...            0.0             0.0
829.0            0.0            0.0  ...            0.0             0.0

[5 rows x 500 columns]

In [0]:
matrix = df_user_book_ratings.values
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
# # matrix는 pivot_table 값을 numpy matrix로 만든 것 
# matrix = df_user_movie_ratings.as_matrix()

# user_ratings_mean은 사용자의 평균 평점 
user_rent_mean = np.mean(matrix, axis = 1)

# R_user_mean : 사용자-영화에 대해 사용자 평균 평점을 뺀 것.
matrix_user_mean = matrix - user_rent_mean.reshape(-1, 1)

In [0]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
matrix.shape

(500, 500)

In [0]:
user_rent_mean.shape

(500,)

In [0]:
matrix_user_mean.shape

(500, 500)

In [0]:
pd.DataFrame(matrix_user_mean, columns = df_user_book_ratings.columns).head()

ISBN  9780060741693  9780198480648  ...  9791195788583  9788993632583 
0            -0.006         -0.006  ...         -0.006          -0.006
1            -0.006         -0.006  ...         -0.006          -0.006
2            -0.008         -0.008  ...         -0.008          -0.008
3            -0.006         -0.006  ...         -0.006          -0.006
4            -0.004         -0.004  ...         -0.004          -0.004

[5 rows x 500 columns]

In [0]:
# scipy에서 제공해주는 svd.  
# U 행렬, sigma 행렬, V 전치 행렬을 반환.

U, sigma, Vt = svds(matrix_user_mean, k = 12)

In [0]:
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(500, 12)
(12,)
(12, 500)


In [0]:
sigma = np.diag(sigma)

In [0]:
sigma.shape

(12, 12)

In [0]:
sigma[0]

array([3.64357473, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [0]:
sigma[1]

array([0.        , 3.65665544, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [0]:
# U, Sigma, Vt의 내적을 수행하면, 다시 원본 행렬로 복원이 된다. 
# 거기에 + 사용자 평균 rating을 적용한다. 
svd_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_rent_mean.reshape(-1, 1)

In [0]:
df_svd_preds = pd.DataFrame(svd_user_predicted_ratings, columns = df_user_book_ratings.columns)
df_svd_preds.head()

ISBN  9780060741693  9780198480648  ...  9791195788583  9788993632583 
0          0.022607      -0.005131  ...       0.004164        0.005587
1         -0.003821      -0.006474  ...       0.000338        0.008168
2         -0.013552       0.028518  ...      -0.001252        0.003399
3         -0.001632       0.000642  ...       0.000275        0.010514
4          0.005503      -0.009280  ...       0.003922        0.002069

[5 rows x 500 columns]

In [0]:
df_svd_preds.shape

(500, 500)

In [0]:
df_rentlist[df_rentlist.회원번호 == 134843]

회원번호           ISBN  value
465  134843.0  9788934937487      1
466  134843.0  9788930231558      1
467  134843.0  9791186560112      1
468  134843.0  9788963720746      1
469  134843.0  9788930231367      1
470  134843.0  9788901072531      1

In [0]:
def recommend_movies(df_svd_preds, user_id, ori_book_df, ori_ratings_df, num_recommendations=5):
    
    #현재는 index로 적용이 되어있으므로 user_id - 1을 해야함.
    # 우리꺼는 아이디가 뒤죽박죽이다 df_svd_preds 인덱스와 df_user_book_ratings 인덱스의 위치가 같도록 바꿔줘야함.
    # ex df_svd_preds의 index 0 은 126번의 책에 대한 예측값이다 (바꿔주기 꽤 어려워 보인다..)
    # 리스트에 인덱스 번호를 자동으로 추가해주는 enumerate 함수로 구했음!!
    # a는 인덱스인 회원번호를 정수형으로 변환
    # b는 enumerate에 조건문을 걸어 입력된 회원번호가 몇번째 인덱스인지 구하기
    # 값을 user_row_number에 저장
    userid_indexing = df_user_book_ratings.index.astype('int')
    userid_index = [i for i,j in enumerate(userid_indexing) if j == user_id]
    user_row_number = userid_index[0]
    
    # 최종적으로 만든 pred_df에서 사용자 index에 따라 영화 데이터 정렬 -> 영화 평점이 높은 순으로 정렬 됌
    sorted_user_predictions = df_svd_preds.iloc[user_row_number].sort_values(ascending=False)
    
    # 원본 평점 데이터에서 user id에 해당하는 데이터를 뽑아낸다. 
    user_data = ori_ratings_df[ori_ratings_df.회원번호 == user_id]
    
    # 사용자 히스토리 불필요해서 삭제
    # 위에서 뽑은 user_data와 원본 영화 데이터를 합친다. 
    # user_history = user_data.merge(ori_book_df, on = 'ISBN').sort_values(['value'], ascending=False)
    
    # 원본 영화 데이터에서 사용자가 본 영화 데이터를 제외한 데이터를 추출
    recommendations = ori_book_df[~ori_book_df['ISBN'].isin(user_data['ISBN'])]

    # 사용자의 영화 평점이 높은 순으로 정렬된 데이터와 위 recommendations을 합친다. 
    recommendations = recommendations.merge( pd.DataFrame(sorted_user_predictions).reset_index(), on = 'ISBN')
    # 컬럼 이름 바꾸고 정렬해서 return
    recommendations = recommendations.rename(columns = {user_row_number: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num_recommendations, :]
                      

    return user_data, recommendations

In [0]:
import time
start = time.time()  # 시작 시간 저장

already_rated, predictions = recommend_movies(df_svd_preds, 136640, df_books, df_rentlist, 10)

print("time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간

time : 0.014408588409423828


In [0]:
predictions

Unnamed: 0           ISBN  ...      주제분류번호 Predictions
365         368  9788971996676  ...       199.2    0.144449
272         275  9788957363058  ...         219    0.125362
79           80  9788930201407  ...  082 911.03    0.100808
306         309  9788960242982  ...         695    0.096496
293         296  9788958286158  ...         653    0.085913
296         299  9788958621799  ...         400    0.081176
159         162  9788937810770  ...         400    0.075267
358         361  9788966070671  ...         410    0.074116
355         358  9788966070350  ...         909    0.063250
104         105  9788930206723  ...         517    0.060410

[10 rows x 6 columns]

In [0]:
already_rated.head(10)

회원번호           ISBN  value
1431  136640.0  9788930232524      1
1432  136640.0  9788926390214      1
1433  136640.0  9788932909974      1

In [0]:
predictions

Unnamed: 0           ISBN  ...      주제분류번호 Predictions
365         368  9788971996676  ...       199.2    0.144449
272         275  9788957363058  ...         219    0.125362
79           80  9788930201407  ...  082 911.03    0.100808
306         309  9788960242982  ...         695    0.096496
293         296  9788958286158  ...         653    0.085913
296         299  9788958621799  ...         400    0.081176
159         162  9788937810770  ...         400    0.075267
358         361  9788966070671  ...         410    0.074116
355         358  9788966070350  ...         909    0.063250
104         105  9788930206723  ...         517    0.060410

[10 rows x 6 columns]